// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkXK5HKwGkoTgDZvanDcvRpEEj-fkHuic',
    appId: '1:726396466735:web:c174f5c33bc8df876a78da',
    messagingSenderId: '726396466735',
    projectId: 'property-management-195b8',
    authDomain: 'property-management-195b8.firebaseapp.com',
    storageBucket: 'property-management-195b8.firebasestorage.app',
    measurementId: 'G-MBN9GBKGPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzADJiXvxFevJbkqjRHz-q4vqR2WfW_Iw',
    appId: '1:726396466735:android:327b04e62afa5d456a78da',
    messagingSenderId: '726396466735',
    projectId: 'property-management-195b8',
    storageBucket: 'property-management-195b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjt5H20DivHDnbKrHYYEOfZhg95GAj9K4',
    appId: '1:726396466735:ios:a6cb94af4f6d8d3b6a78da',
    messagingSenderId: '726396466735',
    projectId: 'property-management-195b8',
    storageBucket: 'property-management-195b8.firebasestorage.app',
    iosBundleId: 'com.example.propertyManagment',
  );
}
